### ISSUE TITLE
toponym_matching/resources/ should be processing/resources

### ISSUE THREAD

**Issue by cfarah-anno** [Living-with-machines/LwM_SIGSPATIAL2020_ToponymMatching#8]
In steps 2 and 3 of the gazeteers.ipynb, markdown indicates to put files in the toponym_matching/resources subdirectory. This should be processing/resources.

**Comment by mcollardanuy** [comment]
Hi @cfarah-anno, thank you for spotting this! I've updated the documentation in https://github.com/Living-with-machines/LwM_SIGSPATIAL2020_ToponymMatching/commit/68d6732d27a0cc34b561b484a1d832d9d662bc3. Thanks!
